# Generated by Django 5.2 on 2025-04-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_parent_login_code_student_login_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='number',
            field=models.CharField(default='0700000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='parent',
            name='login_code',
            field=models.CharField(default=0, max_length=6, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='login_code',
            field=models.CharField(default=0, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
