# Generated by Django 5.2 on 2025-04-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_teacher_number_alter_parent_login_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='login_code',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
    ]
