# Generated by Django 5.2 on 2025-04-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_teacher_login_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='login_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
