# Generated by Django 5.2 on 2025-04-25 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_group_curator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='curator',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='students.teacher'),
        ),
    ]
